// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjexthvltximqybdipuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqZXh0aHZsdHhpbXF5YmRpcHVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5ODc5MjUsImV4cCI6MjA3NjU2MzkyNX0.duX9Y_hV3wBpxDKbBTofvxsWXvBE-Pb4y9JIdAnu9PY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});